### ISSUE TITLE
Feature: Start AnyStatus minimized

### ISSUE THREAD

**Issue by gtaylor1981** [AnyStatus/Support#109]
When using the feature 'Run when Windows starts', I would find it useful to be have a 'start minimized' option, so that the main window does not open (until the task icon is double-clicked in the system tray).

**Comment by AlonAm** [comment]
I agree. I think it should start minimized by default without adding that checkbox to the options windows. Do you agree?

**Comment by gtaylor1981** [comment]
Yes, starting minimized by default sounds good (consistent with other apps that run in the system tray).
The only negative is that it would be a breaking change for users who like the current behavior. They might request a 'open status window on start' option.

**Comment by AlonAm** [comment]
@gtaylor1981 the feature has been implemented and released in version 2.9 which you can download from our downloads page at https://www.anystat.us/downloads (unstable)

**Comment by AlonAm** [comment]
Added new configuration setting. Note: this feature is not available for Windows Store.

![image](https://user-images.githubusercontent.com/3127610/64765110-367e7a00-d54c-11e9-801a-c74b9b00851b.png)

**Comment by gtaylor1981** [comment]
Great, thanks!
