### ISSUE TITLE
Stuck sub-pixel in application icon

### ISSUE THREAD

**Issue by elmuerte** [AnyStatus/Support#121]
Not really a stuck pixel, but I thought it was. There is a green pixel in the application icon, upper right corner:
![](https://i.imgur.com/XQQ9pmW.png)

v2.4.25

**Comment by AlonAm** [comment]
I am aware of it but thanks for reporting.
I've tried to get rid of it with no success because it is made of several icons. And, I am looking for a new logo or a designer

**Comment by AlonAm** [comment]
Released in 2.5.22
