### ISSUE TITLE
Links in help do not open

### ISSUE THREAD

**Issue by frackham** [AnyStatus/Support#129]
Win 10, version 2.5.17.

Mailto links work fine, rest of links (e.g. documentation/support) don't.

(Could be no protocol?).

Also, possible to have a direct link to changelog?

**Comment by AlonAm** [comment]
I'll check. Thanks for reporting.

**Comment by AlonAm** [comment]
@frackham what happens when do: Windows Start -> Run -> https://www.google.com ?
Does it open a web browser?

**Comment by frackham** [comment]
Yes, it does. I use Chrome as my main browser. No problem with other
browsers either (through menu or normal browsing).

If no-one else is experiencing this it is most likely my setup (probably
managed settings issue as this is a corporate environment), but not
experiencing this with other desktop apps (node, electron, Vs code etc).

**Comment by frackham** [comment]
Don't know whether just my environment, or fixed in patch, but working perfectly as of 2.5.23, thanks.

**Comment by AlonAm** [comment]
@frackham I've added a direct link to the release notes from Settings -> Help
