### ISSUE TITLE
Feature: TFS Release Plugin

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#13]

**Comment by AlonAm** [comment]
released in 1.4

**Comment by josdeweger** [comment]
First of all, just tried AnyStatus to monitor our TFS builds, looks awesome!

I'm looking for a way to also monitor releases in TFS 2017 update 2 (15.117.26714.0), but I can not seem to find this functionality. Am I missing something here?

**Comment by AlonAm** [comment]
Not sure why I closed this issue, I guess it was the VSTS release.

TFS releases are not yet supported, it is on our roadmap.

Technically, TFS and VSTS is the same API thus the VSTS widget is due to replace the TFS widget sometime soon.

**Comment by josdeweger** [comment]
sounds good, any idea about an ETA? Maybe something I can do to help?

**Comment by AlonAm** [comment]
No ETA at the moment (sorry, I'm alone here). Feel free to have a look at the VSTS Client and Widget source code at https://github.com/AnyStatus/Plugins/tree/master/src/AnyStatus.Plugins/Widgets/VSTS

The only difference between VSTS and TFS is the server URL.

The plan is to introduce a new version of TFS widgets that will use the same VSTS Client.

I'll start working on it this weekend :-)
