### ISSUE TITLE
Bug: Window doesn't remember previous location when restored from the system tray

### ISSUE THREAD

**Issue by tobysmith568** [AnyStatus/Support#131]
v2.5.22

**Comment by AlonAm** [comment]
Yes, this is new...

**Comment by AlonAm** [comment]
This was cause because the ensure-in-view check was called before the window is visible.
Released a quick fix in 2.5.23 by ensuring the window is in view only when window state change.

**Comment by AlonAm** [comment]
@tobysmith568 it's not a perfect solution but I think it's good enough. Let me know if you experience any issues.
