### ISSUE TITLE
Feature: Logical Drive % Free Space

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#137]
Same as using Performance Counter with
Category: LogicalDisk
Counter: % Free Space
Instance: C:

The plugin should show a drop-down list of logical drives.

**Comment by AlonAm** [comment]
Not sure how to name it.

**Comment by AlonAm** [comment]
Also, not sure whether it should be % free space or % used space

**Comment by tobysmith568** [comment]
I think percentage used? It'll copy the drive in My Computer then:
![image](https://user-images.githubusercontent.com/22356255/59607324-0a995700-910b-11e9-8ecb-ec4978cdeabc.png)

**Comment by AlonAm** [comment]
Agree. I prefer the "% Used" version too.
Note, the performance counter gives you the "% Free"...thus, it may not be useful in our case.

**Comment by AlonAm** [comment]
It would be nice to see the same description in the widget tooltip. For example: 76 GB free of 237 GB
