### ISSUE TITLE
Elasticsearch Plugins

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#160]
New plugins pack for Elasticsearch

**Comment by fatihboy** [comment]
Published 0.2.11 version on [nuget.org](https://www.nuget.org/packages/AnyStatus.Plugins.Elasticsearch/0.2.11) with no System.Diagnostics.DiagnosticSource dependency.

**Comment by AlonAm** [comment]
Great, thank you very much for the update

**Comment by AlonAm** [comment]
Released in 2.7.20
