### ISSUE TITLE
Empty entries on github issues widget

### ISSUE THREAD

**Issue by fatihboy** [AnyStatus/Support#162]
When multiple github issues widgets added empty entries shown. Please refer screetshot.
![AnyStatus-empty github issues](https://user-images.githubusercontent.com/1845475/63184746-bf46ea80-c060-11e9-964a-a4944babeeb3.png)

**Comment by AlonAm** [comment]
Thanks for the feedback, I'll check.

**Comment by AlonAm** [comment]
I'm unable to reproduce this issue using in version 2.7

**Comment by fatihboy** [comment]
I've try again with 2.7.21 and hit github api rate limit. Could it be releted with exception handling?

**Comment by AlonAm** [comment]
I don't think it's related. When APi rate limit occurs the widget fail (red). Let's try again on another day and see if it happens again.
