### ISSUE TITLE
Feature: provide a way to format Metric and Sparkline display value

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#164]
_Originally posted by @fatihboy in [comment](https://github.com/fatihboy/AnyStatusElasticsearch/issues/1#issuecomment-522361508)._.

Is there any way to write kb/mb/gb values to marked area while stil use bytes on sparkline?

![image](https://user-images.githubusercontent.com/3127610/63247140-fb4e9b00-c26c-11e9-8126-9e1c41a1b11d.png)

**Comment by AlonAm** [comment]
@fatihboy this is not yet supported but it's a good idea.

You can set the [Symbol](https://github.com/AnyStatus/API/blob/018082be2e916ef27b8b2bf2d54c01c3f920d5c5/src/AnyStatus.API/Widgets/Types/Metric.cs#L25) property to show something next to the number but there's no option yet to format the value.

Here are some ideas

1. Add something like [IFormatProvider](https://docs.microsoft.com/en-us/dotnet/api/system.iformatprovider?view=netframework-4.8) property to Metric.
2. Add DisplayValue property to Metric in addition to Value.
3. Create a new Sparkline/Metric type that is dedicated to sizes.

What's your opinion? Any other ideas?

**Comment by fatihboy** [comment]
My vote goes option 1 :)
Do we still need Symbol property anymore with these options?

**Comment by AlonAm** [comment]
Not sure we still need Symbol
I'll play around with format provider and see how it goes

**Comment by AlonAm** [comment]
@fatihboy I didn't find a way to "inject" IFormatProvider to the XAML.

What I'm suggesting is to enable overriding the ToString function on the Metric where you can transform the output as you like. See [here](https://github.com/AnyStatus/API/blob/286931957cde0a962bef72dafccd3f3cb3dc8056/src/AnyStatus.API/Widgets/Types/Metric.cs#L35).

Also, you can leave the Symbol property empty and specify it in the ToString instead.

What's your opinion?

**Comment by fatihboy** [comment]
It's ok for me. I'll just override the function to provide my own format.

**Comment by AlonAm** [comment]
As part of this change I am canceling the Symbol property as it is not needed

**Comment by AlonAm** [comment]
Add [Bytes Formatter](https://github.com/AnyStatus/API/blob/master/src/AnyStatus.API/Common/Utils/BytesFormatter.cs) utility to API. See [examples](https://github.com/AnyStatus/API/blob/master/src/AnyStatus.API.Tests/Common/BytesFormatterTests.cs).

**Comment by AlonAm** [comment]
Released in 2.7.29
The UI now uses the ToString method to get the display value.
The ToString can be overridden in derived classes to provide different formatting.
See [Network Speed](https://github.com/AnyStatus/Plugins/blob/master/src/AnyStatus.Plugins/Widgets/SystemInformation/Network/Speed/NetworkSpeed.cs) for example.

![image](https://user-images.githubusercontent.com/3127610/63429934-10b9f580-c424-11e9-855a-fcd8a6fa14e3.png)
