### ISSUE TITLE
Feature: Make settings encryption optional, or only encrypt secrets in the settings

### ISSUE THREAD

**Issue by bender-the-greatest** [AnyStatus/Support#165]
I use the Jenkins plugin (not sure if it matters here), and it seems that all of my job monitoring settings may be behind an EncryptedData element in the config file. We replace our Jenkins farm 4 times a year, and with other monitoring tools I am able to regex replace the URLs and job names in the config with the new ones when this changeover occurs. I am unable to do this with AnyStatus which makes it difficult to adopt for my team's workflow. It also seems a bit much to encrypt all of the job information when only secrets (e.g. credential password) really need to be obfuscated from prying eyes.

I was able to find a workaround for now however, I can export the settings, change them there, and re-import. However, this makes it difficult to script this change for our devops toolset.

**Comment by AlonAm** [comment]
Yes, that can be made optional

**Comment by AlonAm** [comment]
Also, I've started adding command line options like import/export which may help with scripting ops

**Comment by AlonAm** [comment]
Released in 2.7.28
@bender-the-greatest Please download and install the unstable version, you'll find the new option in the Settings window.
