### ISSUE TITLE
DevOps All repos Pull Requests

### ISSUE THREAD

**Issue by stefanoPrimo** [AnyStatus/Support#180]
Hi,
is there something that I could use for getting all PR from all Repos within 1 configuration? 
Like the Work Item config, it will create a folder containing all repositories.

Let me know

**Comment by AlonAm** [comment]
Thank you for your feedback
Agree this feature is needed (for my work too)
I will try to add it in version 3 which is currently in early preview

**Comment by AlonAm** [comment]
The feature has been released AnyStatus v3
Currently, it only shows the status of the pull request
I'll add more options such as opening the pull requests in the browser, in future versions.
Thank you for your feedback!
