### ISSUE TITLE
Store version lacking functionality

### ISSUE THREAD

**Issue by MatthewSteeples** [AnyStatus/Support#181]
We've been using the store version for quite some time, but the latest update has broken all of the functionality for us.

- Old config files no longer usable (can we migrate them?)
- Azure DevOps doesn't appear to be an option anymore (looks like no plugins are available)

**Comment by AlonAm** [comment]
Hi Mathew,
Apologies for the inconvenience.
Version 2.9 is still available on the website.
According to the store stats I expected the update to have little impact on existing users, as the majority of them used the website to install the app. Lesson learned.

Version 3 is currently in preview to get early feedback from users. Missing plugins, such TFS/Azure/Jenkins will be added later.
