### ISSUE TITLE
Stop adding back removed jobs on refresh

### ISSUE THREAD

**Issue by ka250107** [AnyStatus/Support#183]
When I add a Jenkins folder (Jenkins view widget) which includes multiple jobs, if I choose to remove (i.e. ignore) some of the jobs they always reappear once the view is refreshed (e.g. after the set interval time). Is it possible to stop this from happening or is there any workaround to do that?

**Comment by AlonAm** [comment]
Thank for your feedback!
This issue will be resolved in AnyStatus 3 where automatically added widgets will not have the same standard context menu but only relevant menu items/actions. The filtering will be specified at the parent level.

**Comment by AlonAm** [comment]
Optionally (you're welcome to suggest alternatives), there will be a context menu item to filter-out specific nodes.

**Comment by AlonAm** [comment]
The issue has been resolved in AnyStatus 3 by preventing users from removing automatically added widgets.
The option to remove a widget will not be available.
I'll add support for ignoring items in future versions.
Thank you for your feedback!
