### ISSUE TITLE
NuGet plugin fetches the wrong version

### ISSUE THREAD

**Issue by dotMorten** [AnyStatus/Support#185]
Add a NuGet widget and make it search for `Xamarin.Forms`
![image](https://user-images.githubusercontent.com/1378165/99467677-c3ad2380-28f3-11eb-99d3-51875abf41d8.png)
Notice that the reported version is `4.3.0.991211`:
![image](https://user-images.githubusercontent.com/1378165/99467714-d6275d00-28f3-11eb-8102-5e3c8e98f47d.png)

Compare to nuget.org where the version is at 4.8.x now:

https://www.nuget.org/packages/xamarin.forms

**Comment by AlonAm** [comment]
Checking...
Looks like v3 also has this issue
![image](https://user-images.githubusercontent.com/3127610/99529616-c4ec5800-29a8-11eb-9c87-6af86f0c3a85.png)

**Comment by AlonAm** [comment]
The API call needs to be improved
https://azuresearch-usnc.nuget.org/query?q=Xamarin.Forms

**Comment by AlonAm** [comment]
This works better https://azuresearch-usnc.nuget.org/query?q=Xamarin.Forms&semVerLevel=2.0.0
I'll add the SemVer 2 support and release a fix asap
may take a while, need to revive v2 release pipeline
v3 is released more often

**Comment by dotMorten** [comment]
This isn't a fix, but with this query you at least only get the specific package:
https://azuresearch-usnc.nuget.org/query?q=packageid:Xamarin.Forms
However still looks like the more recent versions are missing.

**Comment by dotMorten** [comment]
Looks good. Perhaps use this instead though to get a bit shorter amount to download and process (and reduce risk of getting the wrong package?):
https://azuresearch-usnc.nuget.org/query?q=packageid:Xamarin.Forms&semVerLevel=2.0.0

**Comment by AlonAm** [comment]
Excellent, thanks!

**Comment by joelverhagen** [comment]
Consider `prerelease=true` if you want to consider pre-release versions in addition to stable versions. By default only stable versions are returned.

Cool system by the way!

**Comment by AlonAm** [comment]
@joelverhagen I'll add an option to include pre-releases as well. Thanks for the feedback!

**Comment by dotMorten** [comment]
Yeah I like that and could use tracking pre releases too

**Comment by AlonAm** [comment]
@joelverhagen is there an option to limit the number of items returned in the versions array?

**Comment by joelverhagen** [comment]
@AlonAm, no there is not. Today the only behavior is all of the **listed** versions for each matched package ID are returned, respecting the `semVerLevel` and `prerelease` criteria.

**Comment by AlonAm** [comment]
@dotMorten I have released the fix for both v2 and v3. AnyStatus now supports semver 2 and pre-release packages, thanks to your feedback. Can you please confirm it works on your machine?

![image](https://user-images.githubusercontent.com/3127610/99876008-9e265f80-2bfc-11eb-841a-a5e69bfc483a.png)

![image](https://user-images.githubusercontent.com/3127610/99876015-aaaab800-2bfc-11eb-8085-65b82eb86385.png)

**Comment by dotMorten** [comment]
Works awesome!

**Comment by dotMorten** [comment]
Wait how did you do that download counter???

**Comment by AlonAm** [comment]
It's a new widget in v3

**Comment by dotMorten** [comment]
FYI I found a way to also get hold of unlisted packages - which is great when you want the scoop on a release before the nuget is fully published. Built my own plugin that uses this (rather rudimentary) approach:
https://github.com/dotMorten/AnyStatus/blob/9909deec862610ed4fc02dca9d9b6b2c7c39f2fc/src/Plugins/AnyStatus.Plugins.dotMorten/NuGetPackageQuery.cs#L28-L34

If you decide to incorporate it, it should probably be an option to turn on, as often you don't want unlisted packages.

**Comment by joelverhagen** [comment]
@dotMorten another approach you can consider if you're interested is to use the "package content" version index if all you need is the version string:
https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#sample-response
e.g. https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
This has all of the prerelease versions James has unlisted over the years.

Also, I would highly recommend using the service index resource to discover that base URL.
https://docs.microsoft.com/en-us/nuget/api/service-index

Over time, we (the NuGet.org team) sometimes changes those base URLs. For the "registration" URLs this has happened 5 times over the years as evidenced by the 5 in the URL.

**Comment by dotMorten** [comment]
@joelverhagen Thanks! That index.json url is MUCH simpler :)
