### ISSUE TITLE
Feature: Jenkins multi-job plugin

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#24]

**Comment by AlonAm** [comment]
@Kolky, I will change the name of the plugin to "Jenkins Multijob" (or Multi Job) since it is useful for other Jenkins views as well, not just branches.

**Comment by Kolky** [comment]
Sure fine with that :)

**Comment by AlonAm** [comment]
The plugin is not yet stable, for example, when adding lots of nodes, the status update is slow.
I'm playing around to stabilize it before it can be released.
feel free to make changes and adjustments too.
Thanks!

**Comment by vatioz** [comment]
Is this feature related to jenkins folders? I would like to add only url to jenkins folder and have AnyStatus show me all jobs inside.

**Comment by AlonAm** [comment]
Yes, that is a new plugin that we're working on will hopefully be released
soon.

**Comment by AlonAm** [comment]
@kolky, I have refactored the Jenkins plugins, the code looks much simpler now. Check it out:
 https://github.com/AnyStatus/Plugins/tree/master/src/AnyStatus.Plugins/Continuous%20Integration/Jenkins

**Comment by AlonAm** [comment]
@Kolky, can I add your name next to the feature in the changelog? Would you like to link your website/blog?
thanks

**Comment by Kolky** [comment]
Feature is a lot better now, looks great!

My name is fine :) (links not needed)

Thanks!

**Comment by AlonAm** [comment]
So, the new feature has been successfully released.
There's still some work to do, but it's good enough for the initial release.
Thank you for the awesome idea! 
You've opened the door for a whole new family of features :-)
For example, the VSTS Release plugin is based on the same concept.
p.s, I've added your name next to the plugin in the [changelog](https://www.anystat.us/docs/changelog).
