### ISSUE TITLE
Feature: specify branch name in TeamCity build

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#46]
asked on twitter: https://twitter.com/Shmuelie/status/925443921630687232

**Comment by AlonAm** [comment]
Source code: https://github.com/AnyStatus/Plugins/blob/master/src/AnyStatus.Plugins/TeamCity/TeamCityBuildMonitor.cs

**Comment by SamuelEnglard** [comment]
I just realized I didn't change Open Webpage to open to the branch

**Comment by AlonAm** [comment]
released in 1.4.101

**Comment by huseyint** [comment]
Can I specify a wildcard to watch all branches?

**Comment by SamuelEnglard** [comment]
Currently no, unless @AlonAm added that?

**Comment by AlonAm** [comment]
No, I didn't

**Comment by huseyint** [comment]
So I should add each branch separately to watch all the branches, correct?

**Comment by AlonAm** [comment]
I think you can leave the branch name empty to watch all branches

**Comment by huseyint** [comment]
Leaving it empty watches only the default branch as far as I can see.

**Comment by AlonAm** [comment]
Feel free to check out the source code to see exactly what it does (it's pretty small). Maybe TC API itself allows wildcards. I'll try to check myself later this week
