### ISSUE TITLE
Feature: More details in status change notifications

### ISSUE THREAD

**Issue by SamuelEnglard** [AnyStatus/Support#48]

**Comment by AlonAm** [comment]
What details would you like to see in the build notification?
btw, any plugin can override any notification. For example: https://github.com/AnyStatus/API/blob/master/src/AnyStatus.API/Widgets/Build.cs#L9

**Comment by SamuelEnglard** [comment]
I'm thinking at the very least a why or the like. Might depend on the source

**Comment by AlonAm** [comment]
Looks good
Can you please paste an example of a build.StatusText message?

**Comment by SamuelEnglard** [comment]
![image](https://user-images.githubusercontent.com/1119883/32328629-ea677d22-bfb0-11e7-82d3-bd496f992d4d.png)

Which corresponds to

![image](https://user-images.githubusercontent.com/1119883/32328687-206eaf6c-bfb1-11e7-8406-bad8168d9ca8.png)

In TeamCity

**Comment by AlonAm** [comment]
Nice!!!

**Comment by AlonAm** [comment]
Makes me wanna work with TeamCity again :-)

**Comment by AlonAm** [comment]
Released in 1.4.101
@SamuelEnglard thank you!
