### ISSUE TITLE
To open source or not open source

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#58]
This thread is a discussion about whether AnyStatus should be *fully* open source or not.
Feel free to express your thoughts and feelings about it.

**Comment by AlonAm** [comment]
@SamuelEnglard, thoughts?

**Comment by SamuelEnglard** [comment]
That's a personal call

**Comment by SpeedHighway** [comment]
Definitely a personal call, but you can always make it so that only pull requests are allowed so you can make sure only code that is a style you like makes it in.  However, if you're concerned about just no one seeing the code, itself, that's another story.

**Comment by SamuelEnglard** [comment]
I think, that with the plugins being open source (and the fact that it just loads any DLL with the right name) you can easily customize what AnyStatus does but still have the Core closed source
