### ISSUE TITLE
Feature: dock window to the side of the screen

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#59]

**Comment by AlonAm** [comment]
released in 1.5.6

**Comment by SpeedHighway** [comment]
Some comments:
1.  When clicking 'Dock' on another monitor, other than primary, it always docks to primary.  This can, at the moment, be resolved by 2.  Can you have it dock to the current monitor, when the button is clicked?
2.  The dock does not actually dock to the screen.  As a result, it can be moved anywhere, and resized, while still thinking it is docked.  Also, it does not appear over other content, despite being docked.  Horizontal sizing is appropriate, but it should really be attached and unmovable.
3.  Is there any chance of having an option for letting it auto-hide until the mouse moves over it?  Have it move/size almost all the way off the screen (but not just "move" or it will show up on other monitors.").

Thanks

**Comment by AlonAm** [comment]
sure, ill release an update with some of your requests soon.
about 3, how would you like to show the window, by moving the mouse over the edge of the screen?
thanks a lot for the feedback

**Comment by SpeedHighway** [comment]
Yes, that sounds about right.  Normally there's about 1-2 pixels showing, indicating that something is there, docked.  

(Also, would there be a way to dock it to the left side of the screen, by chance?)

Thanks for all of your work on this great tool.

**Comment by AlonAm** [comment]
sure, ill add an option to choose the docking. ill create another issue to take care of it in upcoming versions :-)

**Comment by AlonAm** [comment]
I have released a new version with some of the requested changes.
the window will now be "locked" and appear above other windows. you can also dock the window to other screens/monitor.
lets give it a try and see how it goes.
thanks a lot for the feedback!

**Comment by AlonAm** [comment]
here's a link to the issue regarding the auto-hide: https://github.com/AnyStatus/Support/issues/67

As a start, ill make the window auto-hide when losing focus.
