### ISSUE TITLE
Bug: redundant jenkins jobs in jenkins view

### ISSUE THREAD

**Issue by bobby-chiu** [AnyStatus/Support#60]
this happens on AnyStatus extension 1.4.101 under vs2017 ver.15.5.1

**Comment by bobby-chiu** [comment]
To be exact, i found any operation can trigger this problem, all jobs will be copied once and displayed in anystatus explorer

**Comment by AlonAm** [comment]
Ill try to reproduce the bug and fix it asap
Thanks for reporting

**Comment by AlonAm** [comment]
i was unable to reproduce the bug. can you please describe what happens when the bug occurs? when you click Refresh, the whole Jenkins View duplicates?

**Comment by AlonAm** [comment]
I am now able to reproduce the bug.
ill try to release a fix asap
thanks for reporting!

**Comment by AlonAm** [comment]
released in 1.6.4
