### ISSUE TITLE
Task: rename setup file name

### ISSUE THREAD

**Issue by vatioz** [AnyStatus/Support#66]
Hi, I was just reinstalling AnyStatus several times and I would like to see better name of the setup file. Currently it looks like this:
![image](https://user-images.githubusercontent.com/14203428/34299196-f0820cca-e721-11e7-8cdf-f2388f723228.png)
Which is not very revealing especially after some time...

I would suggest something like **AnyStatus_desktop_[version].exe**.

Icon for the file would be nice topping, but is not really necessary.

**Comment by AlonAm** [comment]
I can change the file name but then ill have to add a task to the automated deployment to update the website button.
I accept your request but it may take some time to implement.
thanks for the feedback!

**Comment by AlonAm** [comment]
The "feature" has been implemented in AnyStatus 2.0 EAP download link (blue button). Once version 2.0 goes live, I will replace the other download link as well (green button).

Thanks for the feedback and for using AnyStatus :-)

**Comment by AlonAm** [comment]
Created a new issue for replacing the installer icon: https://github.com/AnyStatus/Support/issues/79
