### ISSUE TITLE
Improvement: change the order of items in the context menu

### ISSUE THREAD

**Issue by bobted** [AnyStatus/Support#88]
When using Jenkins View for a multibranch pipeline, the Remove context menu item is available for each branch within the job. If a branch is deleted using the menu item, it reappears during the next refresh of the Jenkins job.

Can this menu item be changed to ignore the selected branch? Either by removing from the list or to show it with a different icon which does not propagate to the overall status.

The root of the issue is a deleted branch which had a last build status of failed. The Jenkins job is setup to scan the repository for deleted branches, but we are retaining the build for 7 days after the branch is deleted. During those 7 days, the overall status shown by AnyStatus is "failed" due to the 1 branch that no longer exists.

**Comment by AlonAm** [comment]
What happens when you disable the deleted branch, from the context menu, and then refresh?
Is it still disabled?

Thank you for the feedback!

**Comment by AlonAm** [comment]
According to my test, if you disable one of the jobs in the view, it stays disabled.
Does that solve the issue?

**Comment by bobted** [comment]
The Disable seems to be what I was looking for. I think when I first saw the option to Disable, I assumed it meant I could disable the Jenkins job in Jenkins, not the status updating within AnyStatus. 

But now that I know it is there, I would suggest a couple things with it: change the icon for Enable/Disable so they are different than the Start, and somehow differentiate options that execute something in CI compared to local application commands.

**Comment by bobted** [comment]
I'll admit that I'm terrible at UI/UX... Limiting the mouse clicks or simply keeping the required input to a minimum seems to be the right approach. My main concern or issue what not being able to discern what the Disable menu item meant, or rather what the scope of that command was.

Maybe it comes down to an additional work with each command. "Start" is "Queue Build" or "Disable" is "Disable Tracking" or something like that. Then you keep a single menu and minimal clicks; however you lose some cleanliness of the UI due to the extra words (if that's a concern).

**Comment by AlonAm** [comment]
Good points.
Do you prefer a flat menu with better text over a sub-menu? (more text is fine)
The Start, in the context of builds, was "Trigger a new build" in previous versions. I changed it because from the API perspective Start and Trigger is the same thing. Now "Start" is used for both builds and windows services (or anything that is startable).
Let me check if I can override the text for specific things like builds.

**Comment by bobted** [comment]
I have no preference between a flat menu with more text vs sub-menus. If you're repeating the same commands but in different context, it maybe better to use sub-menus. 

Just thinking in the context of something like reusing a view model for the sub-menus that only hold their menu items. Whenever a user clicks on "Start", the sub-menu calls back to it's parent that start was called. The parent menu item can either handle the event or raise it's own event with a actual command to fire: CI Build Start vs Start Tracking Build Status.

**Comment by AlonAm** [comment]
Here's an alternative layout proposal. In this layout the actions that are "remote" will be shown under "All Tasks" such as Start, Stop, Restart, Approve, etc. The "Open in Browser" option will be visible above "All Tasks" for easy access. Underneath, there's a group of "general" commands, such as disable/enable, copy, paste, etc.

![image](https://user-images.githubusercontent.com/3127610/40567170-ed78e344-607c-11e8-8c98-bd4350439d86.png)

I think "All Tasks" sub-menu makes it obvious that this is a different type of a command.
And, the additional step of opening the sub-menu, makes you double-think before you click the Start button.
What do you think?

**Comment by AlonAm** [comment]
Thank you very much for your inputs!
I'll release this change in upcoming release.
Please do not hesitate to reach out for further refinement or any other issue.
Thank you for using AnyStatus :-)

**Comment by AlonAm** [comment]
Released in 2.1.12
@bobted  thank you for your feedback!

**Comment by bobted** [comment]
Glad I could contribute. I installed 2.1.12 yesterday. Looks good.
