### ISSUE TITLE
Bug: AnyStatus Desktop window hides when docked

### ISSUE THREAD

**Issue by AlonAm** [AnyStatus/Support#90]

**Comment by AlonAm** [comment]
a fix was released in 2.1.18

**Comment by andrejohansson** [comment]
Are you sure? I have v2.4.25 and running on windows 10. When I dock AnyStatus it hides as soon as it doesnt have focus.

**Comment by AlonAm** [comment]
There was a bug prior to v2.1 in which the window disappeared when docked.

I am aware that the docking mode is not perfect but are you satisfied with current behavior?
Is there something you would like to change?

My thoughts are to make the background blurry (optional) and the window fading and sliding like the windows action center.

**Comment by andrejohansson** [comment]
Hmm, as I wrote I'm running v2.4.25 and still it hides if not having focus.

It seems that AnyStatus is doing something "non standard" regarding the window, could this be true?

I would be very happy if the docking would not hide OR if window managers like [MaxTo](https://maxto.net/) were able to control the AnyStatus window. But as of now, it does not seem possible.

**Comment by AlonAm** [comment]
The window hides when loosing focus by design (when docked). It is designed to behave like the Windows Action Center. In this context, the docking is non-standard. It simply snaps the window to the side and auto-hides it when loosing focus. What would be the correct behavior in your opinion?

As for MaxTo, thanks for the reference. I am not familiar with this app and will try to make it work together further down the road.

**Comment by AlonAm** [comment]
I have created an issue for MaxTo to learn more about its requirements.
https://github.com/digitalcreations/MaxTo/issues/381

**Comment by AlonAm** [comment]
Created a new dedicate issue for MaxTo support: #149
